ass 1

diff --git a/ass1/assn1/autotest b/ass1/assn1/autotest
--- a/ass1/assn1/autotest
+++ b/ass1/assn1/autotest
@@ -2,70 +2,87 @@
 
 QNAME="listIteratorInt"
 BIN="testListIterInt"
+ALLARG="1 2 3 4 5 6 7 8 9 10 11 12"
 
-echo
-echo "                      $QNAME Test Report"
-if ! which colordiff &> /dev/null
+if make
 then
-    echo "Try 'sudo apt-get install colordiff' before excuting this script to get a more readable result"
-fi
-echo
 
-if [ ! -f "$BIN" ]
-then
-    echo "No such executable: $BIN"
-    exit 1
-fi
+    # generate title
+    echo
+    echo "$QNAME Test Report"
+    echo "----------------------"
 
-if [ ! -x "$BIN" ]
-then
-    echo "$BIN is not executable"
-    exit 1
-fi
-
-if [ ! -d tests ]
-then
-    echo "No tests/ directory here. Are you in the right directory?"
-    exit 1
-fi
-
-
-if [ "$#" -eq 0 ]
-then
-    tsts="1 2 3"
-elif [ "$#" -eq 1 ]
-then
-    tsts="$1"
-else
-    echo "Usage-1: autotest  "
-    echo "Usage-2: autotest <test-number> "
-    exit 1
-fi
-
-for t in $tsts
-do
-
-    ./testListIterInt $t | head -500 > tests/$t.out
-    if cmp -s tests/$t.out tests/$t.exp
+    # check whether colordiff has been installed or not
+    if ! which colordiff &> /dev/null
     then
-        echo -e "\e[32m                             Test $t Passed\e[39m"
-        echo "The Output"
-        echo "----------- "
-        cat tests/$t.out
-        echo
-    else
-        echo -e "\e[31m                             Test $t Failed\e[39m"
-        echo "Your Output                                                    Expected Output"
-        echo "-----------                                                    ---------------"
-        if which colordiff &> /dev/null
-        then
-            diff -y tests/$t.out tests/$t.exp | colordiff
-        else
-            diff -y tests/$t.out tests/$t.exp
-        fi
-        echo
+        echo -e "\e[31mIf you want a more colorful and readable result. Try:\e[39m"
+        echo -e "\e[31m'sudo apt-get install colordiff' before excuting autotest.\e[39m"
     fi
-done
+
+    # check whether the test file exists
+    if [ ! -f "$BIN" ]
+    then
+        echo "No such executable: $BIN"
+        exit 1
+    fi
+
+    # check whether the test file is excutable
+    if [ ! -x "$BIN" ]
+    then
+        echo "$BIN is not executable"
+        exit 1
+    fi
+
+    # check whether the test directory exists
+    if [ ! -d tests ]
+    then
+        echo "No tests/ directory here. Are you in the right directory?"
+        exit 1
+    fi
+
+    # handle the arguments
+    if [ "$#" -eq 0 ]   # if no argument
+    then
+        tsts=$ALLARG
+    elif [ "$#" -eq 1 ] # if 1 argument
+    then
+        tsts="$1"
+    else                # if more than 1 argument, print help message
+        echo "Usage-1: autotest  "  
+        echo "Usage-2: autotest <test-number> "
+        exit 1
+    fi
+
+    # generate test report
+    for t in $tsts
+    do
+        # generate test output file
+        ./testListIterInt $t | head -500 > tests/$t.out
+        if diff -i -Z -b tests/$t.out tests/$t.exp &> /dev/null
+        then        # if test passed
+            echo -e "\e[32m                             Test $t Passed\e[39m"
+            if [ "$#" -eq 1 ]   # test detail is only print when there is only one argument
+            then
+                echo "The Output"
+                echo "----------- "
+                cat tests/$t.out
+            fi
+        else        # if test failed
+            echo -e "\e[31m                             Test $t Failed\e[39m"
+            echo "Your Output                                                    Expected Output"
+            echo "-----------                                                    ---------------"
+            if which colordiff &> /dev/null     # using different output, depend on whether colordiff has been installed
+            then
+                diff -y -i -Z -b tests/$t.out tests/$t.exp | colordiff
+            else
+                diff -y -i -Z -b tests/$t.out tests/$t.exp
+            fi
+            echo
+        fi
+    done
+else
+    exit 1
+fi
 
 
 
